"""empty message

Revision ID: 1329cc1d89df
Revises: 3a0073419908
Create Date: 2015-06-01 22:03:16.927671

"""

# revision identifiers, used by Alembic.
revision = '1329cc1d89df'
down_revision = '3a0073419908'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('parent_reddit_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thing', 'parent_reddit_id')
    ### end Alembic commands ###
