"""empty message

Revision ID: 432eda11066a
Revises: 582255b4e5d
Create Date: 2015-06-01 23:06:23.846537

"""

# revision identifiers, used by Alembic.
revision = '432eda11066a'
down_revision = '582255b4e5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('submission_reddit_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'thing', 'thing', ['submission_reddit_id'], ['reddit_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thing', type_='foreignkey')
    op.drop_column('thing', 'submission_reddit_id')
    ### end Alembic commands ###
