"""empty message

Revision ID: 8dfd59b6836
Revises: 432eda11066a
Create Date: 2015-06-03 00:35:40.242320

"""

# revision identifiers, used by Alembic.
revision = '8dfd59b6836'
down_revision = '432eda11066a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('flair_text', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'thing', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thing', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thing', type_='foreignkey')
    op.drop_column(u'thing', 'user_id')
    op.drop_table('user')
    ### end Alembic commands ###
