"""empty message

Revision ID: c352487997f
Revises: None
Create Date: 2015-05-30 03:36:23.420825

"""

# revision identifiers, used by Alembic.
revision = 'c352487997f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('author_username', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'author_username')
    ### end Alembic commands ###
